import React, { useState, useEffect } from 'react';
import { Paper } from './types/Paper';
import { ApiService, PapersResponse } from './services/api';
import PaperCard from './components/PaperCard';
import './App.css';

function App() {
  const [papers, setPapers] = useState<Paper[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [limit, setLimit] = useState<number>(10);
  const [category, setCategory] = useState<string>('cs.AI');

  const fetchPapers = async () => {
    try {
      setLoading(true);
      setError(null);
      const response: PapersResponse = await ApiService.getPapers(limit, category);
      setPapers(response.papers);
    } catch (err: any) {
      console.error('Failed to fetch papers:', err);
      setError(err.response?.data?.error || 'Failed to fetch papers. Please check if the backend is running.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPapers();
  }, [limit, category]);

  const handleRefresh = () => {
    fetchPapers();
  };

  const categories = [
    { value: 'cs.AI', label: 'Artificial Intelligence' },
    { value: 'cs.LG', label: 'Machine Learning' },
    { value: 'cs.CL', label: 'Natural Language Processing' },
    { value: 'cs.CV', label: 'Computer Vision' },
    { value: 'cs.RO', label: 'Robotics' },
    { value: 'stat.ML', label: 'Statistics - Machine Learning' }
  ];

  return (
    <div className="app">
      <header className="app-header">
        <div className="container">
          <h1 className="app-title">🤖 arXiv AI Research Summarizer</h1>
          <p className="app-description">
            Latest AI research papers with AI-generated summaries powered by Claude
          </p>
        </div>
      </header>

      <main className="main-content">
        <div className="container">
          <div className="controls">
            <div className="control-group">
              <label htmlFor="category-select">Category:</label>
              <select
                id="category-select"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="control-select"
              >
                {categories.map((cat) => (
                  <option key={cat.value} value={cat.value}>
                    {cat.label}
                  </option>
                ))}
              </select>
            </div>

            <div className="control-group">
              <label htmlFor="limit-select">Papers:</label>
              <select
                id="limit-select"
                value={limit}
                onChange={(e) => setLimit(Number(e.target.value))}
                className="control-select"
              >
                <option value={5}>5 papers</option>
                <option value={10}>10 papers</option>
                <option value={20}>20 papers</option>
                <option value={30}>30 papers</option>
              </select>
            </div>

            <button onClick={handleRefresh} className="refresh-button" disabled={loading}>
              🔄 {loading ? 'Loading...' : 'Refresh'}
            </button>
          </div>

          {error && (
            <div className="error-message">
              <h3>❌ Error</h3>
              <p>{error}</p>
              <button onClick={handleRefresh} className="retry-button">
                Try Again
              </button>
            </div>
          )}

          {loading && (
            <div className="loading-state">
              <div className="loading-spinner"></div>
              <p>Fetching papers and generating summaries...</p>
              <p className="loading-note">This may take a moment as we generate AI summaries</p>
            </div>
          )}

          {!loading && !error && papers.length === 0 && (
            <div className="empty-state">
              <h3>📄 No Papers Found</h3>
              <p>No papers found for the selected category. Try a different category or refresh.</p>
            </div>
          )}

          {!loading && !error && papers.length > 0 && (
            <>
              <div className="results-header">
                <h2>📚 Latest {category} Papers ({papers.length})</h2>
                <p>Summaries generated by Claude AI</p>
              </div>

              <div className="papers-grid">
                {papers.map((paper) => (
                  <PaperCard key={paper.id} paper={paper} />
                ))}
              </div>
            </>
          )}
        </div>
      </main>

      <footer className="app-footer">
        <div className="container">
          <p>
            Powered by{' '}
            <a href="https://arxiv.org" target="_blank" rel="noopener noreferrer">
              arXiv
            </a>{' '}
            and{' '}
            <a href="https://anthropic.com" target="_blank" rel="noopener noreferrer">
              Claude AI
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}

export default App;
